#!/bin/bash
#source ~/anaconda3/etc/profile.d/conda.sh

#--#!/home/arunimb/miniconda3/envs/tf_test/bin/python

#The name this job 
#PBS -N tensorFlowRun

#PBS -j oe

#--#PBS -l select=1:ncpus=1:ngpus=1:mem=32gb


#PBS -m abe
#PBS -l ncpus=16
#PBS -l ngpus=1
#--#PBS -q gpuq
#PBS -l mem=64GB
#PBS -l walltime=48:00:00

echo "The job working directory \$PBS_O_WORKDIR is $PBS_O_WORKDIR"
source ~/.bashrc
conda activate tf_test
cd $PBS_O_WORKDIR       
#
#Print out PBS environment variables
echo "#============="

echo "PBS Environment variables, can be used in the job submission scripts as \$PBS_VARNAME"
env | grep PBS
echo "#============="
echo "For example,we can find the number NPmpi of allocated MPI processes as"
echo "NPmpi=\"\$(cat \$PBS_NODEFILE | wc -l)\"" 
NPmpi="$(cat $PBS_NODEFILE | wc -l)" 
echo "NPmpi=$NPmpi"
#
# Print out when and wher this job starts
echo '****************************************************'
echo "Job starting at: `date` at compute node `hostname`"
echo '****************************************************'
# Uncomment 'set -x' to enable a mode of the shell 
# where all executed commands are printed to the output file.
# (may help to visualize the control flow of the script if it is not functioning as expected)
#set -x 
#
echo "Loading required environment modules"
module purge; module load cuda/cuda-12.2  # run with cuda 12.2 other versions seem to fail
# List the loaded modules
#export PATH=$HOME/miniconda3/bin:$PATH
#conda init
#conda activate tf_test
source ~/miniconda3/etc/profile.d/conda.sh
conda activate tf_test
# Run the program 'cudaMPI', expected to be present in the submission folder
# ('./' is the path to the current directory)
echo "StartingTensorFlowJob"
python3 kFoldMultilabel_Inference.py
set +x
echo '****************************************************'
echo "Job completed at: `date` at compute node `hostname`"
echo '****************************************************'
